#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

yum install -y wget
yum install -y vim

yum remove -y mariadb-libs mariadb-config mariadb-common

wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
rpm -ivh mysql-community-release-el7-5.noarch.rpm

# mysql 5.5
#sed -i "19s/enabled=0/enabled=1/" /etc/yum.repos.d/mysql-community.repo
#sed -i "27s/enabled=1/enabled=0/" /etc/yum.repos.d/mysql-community.repo

# default
# mysql 5.6

# mysql 5.7
# sed -i "27s/enabled=1/enabled=0/" /etc/yum.repos.d/mysql-community.repo
# sed -i "36s/enabled=0/enabled=1/" /etc/yum.repos.d/mysql-community.repo

rm -rf /etc/my.cnf
yum swap -y mariadb-libs mysql-community-libs
yum remove -y mariadb-config mariadb-common

yum install -y mysql-server

sudo mkdir -p /etc/mysql
sudo chown mysql:mysql -R /etc/mysql
mkdir -p /etc/my.cnf.d/conf.d
if [ -d /etc/mysql/conf.d ]; then
    rm -rf /etc/mysql/conf.d
fi
ln -s /etc/my.cnf.d/conf.d /etc/mysql
ln -s /etc/my.cnf /etc/mysql/my.cnf

# Bind MySQL service to all network interfaces.
#sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/my.cnf

#set enable InnoDB, UTF-8character set, and UTF-8 collation by default
#sed -i "/bind-address/a\default-storage-engine = innodb\n\
#collation-server = utf8_general_ci\n\
#init-connect = 'SET NAMES utf8'\n\
#character-set-server = utf8" /etc/mysql/my.cnf

if [ ! -d /var/run/mysqld ]; then
    mkdir -p /var/run/mysqld
    chown mysql. /var/run/mysqld
fi

MYSQL_SYSTEMD_D="/etc/sytemd/system/mysqld.service.d"
if [ ! -d $MYSQL_SYSTEND_D ]; then
    mkdir -p $MYSQL_SYSTEMD_D
fi
echo "[Service]" > $MYSQL_SYSTEMD_D/limits.conf
echo "LimitNOFILE=65535" >> $MYSQL_SYSTEMD_D/limits.conf
