#!/bin/bash

set -e
set -o xtrace

if [ "${DISTRO}" != "ubuntu" ]; then
    # Copy service file
    dd if=/tmp/in_target.d/openstack-trove-guestagent.service of=/usr/lib/systemd/system/openstack-trove-guestagent.service

    # Configuring permissions
    chown trove:trove /etc/trove
    chown trove:trove /usr/share/trove
    chown trove:trove /var/log/trove
    #sudo mv /etc/trove/guest_info /etc/guest_info
    cp /etc/trove/trove-guestagent.conf /etc/trove-guestagent.conf
    chgrp trove /etc/trove-guestagent.conf
    mv /etc/trove/trove-guestagent.conf /etc/trove/trove-guestagent.conf-$(date +%F-%H%M%S).back
    ln -s /etc/trove-guestagent.conf /etc/trove/trove-guestagent.conf
    #sudo chmod 0755 /etc/guest_info
    #chown trove:trove /etc/guest_info
    # Enable and start service
    systemctl enable openstack-trove-guestagent.service
    systemctl start openstack-trove-guestagent.service
fi
